server {
    listen 80;
    server_name design-patterns.local;

    root /app;
    index index.php;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log warn;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /app$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT /app;
    }
}