server {
    listen 80;
    server_name design-patterns.local;

    root /app/public;
    index index.php;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log warn;

    # Скрытые файлы: .env, .env.example, .gitignore и т.д.
    location ~ (^|/)\. {
        access_log off;
        log_not_found off;
        return 404;
    }

    # composer / readme / license / makefile / архив
    location ~* ^/(composer\.(json|lock)|README\.md|LICENSE(\.md)?|Makefile|archive_2023\.zip)$ {
        access_log off;
        log_not_found off;
        return 404;
    }

    # YAML файлы
    location ~* \.(yml|yaml)$ {
        access_log off;
        log_not_found off;
        return 404;
    }

    # Служебные директории проекта
    location ^~ /config/ {
        access_log off;
        log_not_found off;
        return 404;
    }

    # Конфигурация Docker
    location ^~ /docker/ {
        access_log off;
        log_not_found off;
        return 404;
    }

    # Пока закрыть
    location ^~ /design-patterns-book/ {
        access_log off;
        log_not_found off;
        return 404;
    }

    # Временные файлы, логи
    location ^~ /var/ {
        access_log off;
        log_not_found off;
        return 404;
    }

    # Статика
    location ^~ /assets/ {
        alias /app/assets/;
        try_files $uri =404;
        access_log off;
        expires 7d;
    }

    location = /favicon.ico {
        try_files /favicon.ico =404;
        access_log off;
        log_not_found off;
    }

    # Главная и fallback
    location / {
        try_files $uri /public/index.php?$query_string;
    }

    # PHP
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /app$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT /app;
    }
}